#!/usr/bin/env python3
"""Generate the reference documentation from the code.

The reference pages under ``docs/reference/`` are derived from the models, the
enums and the transport registry, so they cannot drift from what the software
does. Nothing here is hand-maintained prose about a config key: the key's own
``Field(description=...)`` in :mod:`maverick.config` is the single copy, and
this script arranges it.

Three rules keep that true, and each one fails the build rather than emitting
something stale:

* every field of every model reachable from :class:`~maverick.config.Config`
  must carry a description;
* every model reachable from ``Config`` must be claimed by a section below;
* every ``self.option("x")`` a transport reads must appear in that transport's
  ``options_doc``.

Hand-written prose lives in ``docs/reference/_*.md`` and is included verbatim,
so the generated page can say things the models cannot.

Usage::

    python scripts/gen_docs.py            # write the pages
    python scripts/gen_docs.py --check    # exit 1 if the pages are out of date
"""

from __future__ import annotations

import argparse
import ast
import inspect
import re
import sys
import textwrap
import types
import typing
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from pydantic import BaseModel  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402

from maverick.config import Config, DisplayConfig  # noqa: E402
from maverick.eink.dither import DitherMode  # noqa: E402
from maverick.eink.pack import FrameFormat  # noqa: E402
from maverick.eink.palette import ColorScheme  # noqa: E402
from maverick.eink.pipeline import FitMode  # noqa: E402
from maverick.transports import available_transports  # noqa: E402
from maverick.transports.base import Transport  # noqa: E402

BANNER = "Generated by scripts/gen_docs.py from src/maverick; do not edit by hand."

DOCS = ROOT / "docs" / "reference"


class GenerationError(RuntimeError):
    """Something in the source stopped a page from being generated honestly."""


# --------------------------------------------------------------------------- #
# Enumerations
#
# The members carry no docstrings of their own, so the meanings below are taken
# from the module docstrings that explain them: dither.py for DitherMode,
# pipeline.py for FitMode, pack.py for FrameFormat and palette.py for
# ColorScheme. A member added without a line here fails generation.
# --------------------------------------------------------------------------- #

ENUM_VALUE_DOCS: dict[str, dict[str, str]] = {
    "DitherMode": {
        "auto": (
            "Diffuse error only where the image is locally busy and snap flat regions "
            "straight to the nearest ink. Photographs still dither; a temperature readout "
            "stays crisp. The default, and the right answer for a dashboard."
        ),
        "none": "Snap every pixel to its nearest ink. Flattest output, hardest gradients.",
        "ordered": (
            "An 8x8 Bayer matrix. Regular texture rather than noise, and cheap; it patterns "
            "large flat fills visibly."
        ),
        "floyd_steinberg": "Classic error diffusion over four neighbours. A good general default.",
        "atkinson": (
            "Diffuses only three quarters of the error, which keeps contrast high and light "
            "areas clean at the cost of some detail."
        ),
        "burkes": "Error diffusion over two rows; smoother than Floyd-Steinberg, slightly softer.",
        "sierra": "Error diffusion over three rows. Smooth gradients, the slowest of the family.",
        "sierra_lite": "A two-row, three-neighbour Sierra. Fast, with more visible structure.",
        "stucki": "Three-row diffusion with a wide kernel. Clean gradients, soft edges.",
        "jarvis": "Jarvis, Judice and Ninke: the widest kernel here. Smoothest, and the softest.",
    },
    "FitMode": {
        "contain": (
            "Scale to fit inside the panel, preserving aspect ratio, and centre it on white. "
            "Nothing is lost and nothing is stretched."
        ),
        "cover": (
            "Scale to cover the panel, preserving aspect ratio, and crop the overflow. "
            "Anchored to the top, so headers survive."
        ),
        "stretch": "Scale to the panel exactly, distorting the aspect ratio if it differs.",
        "crop": (
            "No scaling: paste the image at the top left of a white canvas and crop whatever "
            "falls outside the panel."
        ),
    },
    "FrameFormat": {
        "packed": (
            "N bits per pixel, pixels left to right, rows top to bottom, each row padded to a "
            "byte boundary. Most greyscale controllers and index-addressed colour panels."
        ),
        "planes": (
            "One 1-bit plane per ink, concatenated. The classic Waveshare black/white plus red "
            "layout, where two full-size buffers are clocked out in sequence."
        ),
        "indexed": (
            "One byte per pixel. Wasteful on the wire, and the simplest thing for a device or "
            "transport that does its own conversion."
        ),
        "png": (
            "A PNG image. What every transport that hands a picture to a library or a "
            "browser wants."
        ),
        "bmp": "A BMP image, for firmware with a BMP decoder and no PNG one.",
    },
    "ColorScheme": {
        "mono": "Black and white only.",
        "bwr": "Black, white and red: one spot ink.",
        "bwy": "Black, white and yellow: one spot ink.",
        "bwry": "Black, white, red and yellow: two spot inks.",
        "gray4": "Four levels of grey.",
        "gray8": "Eight levels of grey.",
        "gray16": "Sixteen levels of grey, as IT8951 controllers drive.",
        "spectra6": "E Ink Spectra 6: black, white, red, yellow, blue and green.",
        "acep7": "Advanced Colour ePaper: the Spectra 6 inks plus orange.",
    },
}

#: The enumerations the configuration refers to, each with the heading it is
#: documented under. A description that names one of these headings is linked
#: to it automatically.
ENUM_SECTIONS: tuple[tuple[type[Enum], str], ...] = (
    (DitherMode, "Dither modes"),
    (FitMode, "Fit modes"),
    (FrameFormat, "Frame formats"),
    (ColorScheme, "Colour schemes"),
)

ENUM_INTROS: dict[str, str] = {
    "FitMode": "How the screenshot is resized onto the panel, before rotation.",
    "FrameFormat": (
        "The byte layout of the delivered frame. Transports that hand a PIL image to a "
        "library never pack a frame at all, so they default to `png`."
    ),
}


# --------------------------------------------------------------------------- #
# Sections
# --------------------------------------------------------------------------- #

@dataclass
class Section:
    """One model rendered as one heading, a table and its validation rules."""

    heading: str
    model: type[BaseModel]
    #: Overrides the model's own docstring as the section's opening prose.
    intro: str = ""

    @property
    def anchor(self) -> str:
        return slugify(self.heading)

    def fields(self) -> list[tuple[str, FieldInfo]]:
        return list(self.model.model_fields.items())


def model_of(annotation: Any) -> type[BaseModel]:
    """The model behind a field annotation, unwrapping `list[...]` and `| None`."""
    for candidate in flatten(annotation):
        if isinstance(candidate, type) and issubclass(candidate, BaseModel):
            return candidate
    raise GenerationError(f"no model found in annotation {annotation!r}")


def flatten(annotation: Any) -> list[Any]:
    """Every leaf of a nested annotation, in order."""
    origin = typing.get_origin(annotation)
    if origin is None:
        return [annotation]
    out: list[Any] = []
    for arg in typing.get_args(annotation):
        out.extend(flatten(arg))
    return out


def build_sections() -> list[Section]:
    """The sections, in the order a user meets the keys."""
    top = Config.model_fields
    display = DisplayConfig.model_fields
    connections = ["home_assistant", "mqtt", "server"]
    nested = ["theme", "image", "render", "schedule", "transport", "pack", "esphome"]

    sections = [Section(name, model_of(top[name].annotation)) for name in connections]
    sections.append(
        Section(
            "Top-level keys",
            Config,
            intro=(
                "Every key at the root of the file. The three above have sections of "
                "their own, and each entry of `displays` is a [display](#displays)."
            ),
        )
    )
    sections.append(
        Section(
            "displays[]",
            DisplayConfig,
            intro=(
                "One entry per physical panel. `id` is the only required key: the keys "
                "beside it override something the panel catalogue already knows, and the "
                "sections they point at are all optional too, so a display that names a "
                "catalogue panel and a dashboard needs almost nothing else."
            ),
        )
    )
    sections.extend(
        Section(f"displays[].{name}", model_of(display[name].annotation))
        for name in nested
    )
    check_every_model_is_documented(sections)
    return sections


def check_every_model_is_documented(sections: list[Section]) -> None:
    """Fail if a model reachable from Config has no section of its own."""
    documented = {s.model for s in sections}
    missing = sorted(
        m.__name__ for m in reachable_models(Config) if m not in documented
    )
    if missing:
        raise GenerationError(
            "these models are reachable from Config but have no section in "
            f"scripts/gen_docs.py: {', '.join(missing)}"
        )


def reachable_models(model: type[BaseModel]) -> set[type[BaseModel]]:
    found: set[type[BaseModel]] = {model}
    for info in model.model_fields.values():
        for leaf in flatten(info.annotation):
            if isinstance(leaf, type) and issubclass(leaf, BaseModel) and leaf not in found:
                found |= reachable_models(leaf)
    return found


# --------------------------------------------------------------------------- #
# Rendering types, defaults and descriptions
# --------------------------------------------------------------------------- #

def anchors_by_model(sections: list[Section]) -> dict[type[BaseModel], str]:
    return {s.model: s.anchor for s in sections}


def render_type(annotation: Any, anchors: dict[type[BaseModel], str]) -> str:
    """A readable rendering of a field's type, for the table."""
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin in (types.UnionType, typing.Union):
        parts = [render_type(a, anchors) for a in args]
        # A field that takes either a duration string or a number of seconds is
        # far clearer shown by example than as `str | float`.
        if str in args and (float in args or int in args):
            parts[args.index(str)] = '`"5m"`'
        return " | ".join(parts)
    if origin is typing.Literal:
        return " | ".join(f"`{a}`" for a in args)
    if origin in (list, set, frozenset):
        return f"`{origin.__name__}` of {render_type(args[0], anchors)}"
    if origin is dict:
        key, value = (render_type(a, anchors) for a in args)
        return f"`dict` of {key} to {value}"
    if origin is tuple:
        return "`[" + ", ".join(render_type(a, anchors).strip("`") for a in args) + "]`"
    if annotation is type(None):
        return "`None`"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " | ".join(f"`{member.value}`" for member in annotation)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        anchor = anchors.get(annotation)
        name = annotation.__name__
        return f"[section](#{anchor})" if anchor else f"`{name}`"
    if isinstance(annotation, type):
        return f"`{annotation.__name__}`"
    return f"`{annotation}`"


def render_constraints(info: FieldInfo) -> str:
    """The numeric bounds pydantic will enforce, as a suffix for the type cell."""
    bounds: dict[str, Any] = {}
    for item in info.metadata:
        for kind in ("ge", "gt", "le", "lt"):
            value = getattr(item, kind, None)
            if value is not None:
                bounds[kind] = value
    low = bounds.get("ge", bounds.get("gt"))
    high = bounds.get("le", bounds.get("lt"))
    if low is not None and high is not None:
        return f", {low} to {high}"
    if low is not None:
        return f", at least {low}"
    if high is not None:
        return f", at most {high}"
    return ""


def render_default(info: FieldInfo) -> str:
    if info.is_required():
        return "**required**"
    try:
        value = info.get_default(call_default_factory=True)
    except TypeError:  # a factory that wants validated data; none here today
        return "*(computed)*"
    return render_value(value)


def render_value(value: Any) -> str:
    if isinstance(value, BaseModel):
        return "*section defaults*"
    if value is None:
        return "*unset*"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, Enum):
        return f"`{value.value}`"
    if isinstance(value, str):
        return f"`\"{value}\"`" if value else "`\"\"`"
    if isinstance(value, (list, tuple)) and not value:
        return "`[]`"
    if isinstance(value, dict) and not value:
        return "`{}`"
    return f"`{value}`"


def cell(text: str) -> str:
    """Text safe to drop into a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def link_sections(text: str) -> str:
    """Turn a mention of one of this page's headings into a link to it."""
    for heading in [h for _, h in ENUM_SECTIONS] + ["Transport options"]:
        text = text.replace(heading, f"[{heading}](#{slugify(heading)})")
    return text


def slugify(heading: str) -> str:
    """A GitHub-style anchor for a heading."""
    slug = heading.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"\s+", "-", slug)


def docstring(obj: Any) -> str:
    """An object's own docstring, never one inherited from a base class."""
    doc = obj.__dict__.get("__doc__") if isinstance(obj, type) else obj.__doc__
    return inspect.cleandoc(doc).strip() if doc else ""


# --------------------------------------------------------------------------- #
# Validators
# --------------------------------------------------------------------------- #

def validator_rules(model: type[BaseModel]) -> list[str]:
    """One line per validator on this model, taken from its docstring."""
    decorators = model.__pydantic_decorators__
    rules: list[str] = []
    for name, decorator in list(decorators.field_validators.items()) + list(
        decorators.model_validators.items()
    ):
        func = getattr(decorator.func, "__func__", decorator.func)
        doc = docstring(func)
        if not doc:
            raise GenerationError(
                f"{model.__name__}.{name} is a validator with no docstring, so the "
                "reference cannot describe what it enforces. Give it one."
            )
        rules.append(" ".join(doc.split()))
    return rules


# --------------------------------------------------------------------------- #
# Transports
# --------------------------------------------------------------------------- #

def options_used(cls: type[Transport]) -> dict[str, bool]:
    """Every `self.option("x")` the class reads, mapped to whether it is required."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    used: dict[str, bool] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (
            isinstance(func, ast.Attribute)
            and func.attr == "option"
            and isinstance(func.value, ast.Name)
            and func.value.id == "self"
        ):
            continue
        if not (node.args and isinstance(node.args[0], ast.Constant)):
            continue
        key = node.args[0].value
        required = any(
            kw.arg == "required" and getattr(kw.value, "value", False) is True
            for kw in node.keywords
        )
        used[key] = used.get(key, False) or required
    return used


def check_transport_options() -> dict[str, dict[str, bool]]:
    """Fail if a transport reads an option it does not document."""
    required_by: dict[str, dict[str, bool]] = {}
    problems: list[str] = []
    for name, cls in sorted(available_transports().items()):
        used = options_used(cls)
        required_by[name] = used
        undocumented = sorted(set(used) - set(cls.options_doc))
        if undocumented:
            problems.append(
                f"{cls.__name__} reads {', '.join(repr(o) for o in undocumented)} "
                "but does not describe it in options_doc"
            )
    if problems:
        raise GenerationError("; ".join(problems))
    return required_by


# --------------------------------------------------------------------------- #
# The configuration page
# --------------------------------------------------------------------------- #

def render_configuration() -> str:
    sections = build_sections()
    anchors = anchors_by_model(sections)
    required_by = check_transport_options()

    out: list[str] = [
        f"<!-- {BANNER} -->",
        "",
        "# Configuration reference",
        "",
        f"> {BANNER}",
        "> Edit the `Field(description=...)` text in `src/maverick/config.py`, or the prose",
        "> in `docs/reference/_configuration.intro.md`, then run `python scripts/gen_docs.py`.",
        "",
        read_include("_configuration.intro.md"),
        "",
    ]

    for section in sections:
        out.append(f"## {section.heading}")
        out.append("")
        intro = section.intro or docstring(section.model)
        if intro:
            out.append(intro)
            out.append("")
        out.append("| Key | Type | Default | Description |")
        out.append("| --- | --- | --- | --- |")
        for name, info in section.fields():
            if not info.description:
                raise GenerationError(
                    f"{section.model.__name__}.{name} has no description, so the "
                    "reference would document it as a blank. Add one in config.py."
                )
            rendered_type = render_type(info.annotation, anchors) + render_constraints(info)
            out.append(
                f"| `{name}` | {cell(rendered_type)} "
                f"| {cell(render_default(info))} "
                f"| {link_sections(cell(info.description))} |"
            )
        out.append("")
        rules = validator_rules(section.model)
        if rules:
            out.append("**Validation.** " + " ".join(rules))
            out.append("")

    out.append(render_enums())
    out.append(render_transports(required_by))
    return "\n".join(out).rstrip() + "\n"


def render_enums() -> str:
    out = ["## Enumerations", ""]
    for enum_cls, heading in ENUM_SECTIONS:
        values = ENUM_VALUE_DOCS[enum_cls.__name__]
        undocumented = [m.value for m in enum_cls if m.value not in values]
        if undocumented:
            raise GenerationError(
                f"{enum_cls.__name__} has values with no description in "
                f"scripts/gen_docs.py: {', '.join(undocumented)}"
            )
        out.append(f"### {heading}")
        out.append("")
        intro = enum_cls.__doc__ or ENUM_INTROS.get(enum_cls.__name__, "")
        if intro:
            out.append(" ".join(intro.split()))
            out.append("")
        out.append("| Value | Meaning |")
        out.append("| --- | --- |")
        for member in enum_cls:
            out.append(f"| `{member.value}` | {cell(values[member.value])} |")
        out.append("")
    return "\n".join(out)


def render_transports(required_by: dict[str, dict[str, bool]]) -> str:
    out = [
        "## Transport options",
        "",
        "`displays[].transport.type` picks a transport; every other key in that section is "
        "the transport's own. They are listed here rather than in the table above because "
        "`TransportConfig` allows extra keys, so the transport, not the model, owns them. "
        "An option a transport does not recognise is ignored rather than rejected.",
        "",
    ]
    for name, cls in sorted(available_transports().items()):
        used = required_by[name]
        out.append(f"### `{name}`")
        out.append("")
        delivery = (
            "Pushes to the device: delivery succeeds or fails now."
            if cls.pushes
            else "Publishes the frame for the device to collect, so a delivery is *pending* "
            "until the device fetches it."
        )
        out.append(f"{cls.description}. {delivery}")
        out.append("")
        if not cls.options_doc:
            out.append("Takes no options of its own.")
            out.append("")
            continue
        out.append("| Option | Required | Description |")
        out.append("| --- | --- | --- |")
        for option, description in cls.options_doc.items():
            required = "yes" if used.get(option) else "no"
            out.append(f"| `{option}` | {required} | {cell(description)} |")
        out.append("")
    return "\n".join(out)


def read_include(name: str) -> str:
    path = DOCS / name
    if not path.exists():
        raise GenerationError(f"missing hand-written include: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8").strip()


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

PAGES: dict[str, Any] = {
    "configuration.md": render_configuration,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write anything; exit 1 if a page is out of date",
    )
    args = parser.parse_args(argv)

    try:
        rendered = {name: render() for name, render in PAGES.items()}
    except GenerationError as exc:
        print(f"gen_docs: {exc}", file=sys.stderr)
        return 1

    stale: list[str] = []
    for name, content in rendered.items():
        path = DOCS / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        if current == content:
            print(f"unchanged {path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote     {path.relative_to(ROOT)}")

    if stale:
        print(
            "gen_docs: out of date: "
            + ", ".join(stale)
            + "\nRun `python scripts/gen_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("gen_docs: reference pages are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
