#!/usr/bin/env python3
"""Generate the reference documentation from the code.

The reference pages under ``docs/reference/`` are derived from the models, the
enums and the transport registry, so they cannot drift from what the software
does. Nothing here is hand-maintained prose about a config key: the key's own
``Field(description=...)`` in :mod:`maverick.config` is the single copy, and
this script arranges it.

Three rules keep that true, and each one fails the build rather than emitting
something stale:

* every field of every model reachable from :class:`~maverick.config.Config`
  must carry a description;
* every model reachable from ``Config`` must be claimed by a section below;
* every ``self.option("x")`` a transport reads must appear in that transport's
  ``options_doc``.

Hand-written prose lives in ``docs/reference/_*.md`` and is included verbatim,
so the generated page can say things the models cannot.

``docs/reference/openapi.json`` is the odd one out: it is not Markdown but
FastAPI's own description of the routes in :func:`maverick.server.api.create_app`,
built here around an empty :class:`~maverick.config.Config` so it depends on no
particular deployment. ``docs/reference/http-api.md`` is hand-written prose
about the same routes and links to it.

Usage::

    python scripts/gen_docs.py            # write the pages
    python scripts/gen_docs.py --check    # exit 1 if the pages are out of date
"""

from __future__ import annotations

import argparse
import ast
import inspect
import json
import re
import sys
import textwrap
import types
import typing
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT / "src") not in sys.path:
    sys.path.insert(0, str(ROOT / "src"))

from pydantic import BaseModel  # noqa: E402
from pydantic.fields import FieldInfo  # noqa: E402

from maverick.app import Application  # noqa: E402
from maverick.cli import build_parser  # noqa: E402
from maverick.config import Config, DisplayConfig  # noqa: E402
from maverick.devices import PanelProfile, panels_by_vendor  # noqa: E402
from maverick.eink.dither import DitherMode  # noqa: E402
from maverick.eink.pack import FrameFormat  # noqa: E402
from maverick.eink.palette import ColorScheme  # noqa: E402
from maverick.eink.pipeline import FitMode  # noqa: E402
from maverick.server.api import create_app  # noqa: E402
from maverick.transports import available_transports  # noqa: E402
from maverick.transports.base import Transport  # noqa: E402

#: Environment variables read directly with os.environ.get across src/maverick,
#: each with the module that reads it. A new one that is not listed here (grep
#: `os.environ` in src/maverick to check) is missing from docs/reference/cli.md.
ENVIRONMENT_VARIABLES: tuple[tuple[str, str], ...] = (
    (
        "MAVERICK_DEBUG",
        "Skip the top-level error handler in `cli.main`, so an unexpected exception "
        "raises with a full traceback instead of being caught and printed with exit "
        "code 1. Any non-empty value turns this on.",
    ),
    (
        "MAVERICK_MAX_RENDERS",
        "Maximum number of Chromium pages rendered concurrently (`engine.Engine`). "
        "Default 2. Each concurrent render can spike Chromium's memory by tens of "
        "megabytes, so raise this only with memory to spare.",
    ),
    (
        "MAVERICK_CHROMIUM_PATH",
        "Path to a Chromium or Chrome executable Playwright did not install itself "
        "(`render.browser.BrowserPool`). Needed wherever Playwright ships no matching "
        "build — notably arm64/aarch64, where the distro `chromium` package is the "
        "only option.",
    ),
    (
        "NO_COLOR",
        "Disable ANSI color in log output (`logging_setup.setup_logging`), even when "
        "stderr is a terminal. The de facto standard; unset it, or leave it empty, to "
        "get color back on a TTY.",
    ),
)

#: main()'s exit codes, in the order cli.py checks for them.
EXIT_CODES: tuple[tuple[str, str], ...] = (
    ("0", "Success."),
    (
        "1",
        "An unhandled exception reached `main`. The message is printed as "
        "`error: <type>: <message>`, with a hint to set `MAVERICK_DEBUG=1` for a "
        "traceback.",
    ),
    (
        "2",
        "A `ConfigError`: the config file was not found, failed to parse, or failed "
        "validation. Printed as `config error: <message>`.",
    ),
    ("130", "Interrupted with Ctrl-C (`KeyboardInterrupt`)."),
)

BANNER = "Generated by scripts/gen_docs.py from src/maverick; do not edit by hand."

DOCS = ROOT / "docs" / "reference"


class GenerationError(RuntimeError):
    """Something in the source stopped a page from being generated honestly."""


# --------------------------------------------------------------------------- #
# Enumerations
#
# The members carry no docstrings of their own, so the meanings below are taken
# from the module docstrings that explain them: dither.py for DitherMode,
# pipeline.py for FitMode, pack.py for FrameFormat and palette.py for
# ColorScheme. A member added without a line here fails generation.
# --------------------------------------------------------------------------- #

ENUM_VALUE_DOCS: dict[str, dict[str, str]] = {
    "DitherMode": {
        "auto": (
            "Diffuse error only where the image is locally busy and snap flat regions "
            "straight to the nearest ink. Photographs still dither; a temperature readout "
            "stays crisp. The default, and the right answer for a dashboard."
        ),
        "none": "Snap every pixel to its nearest ink. Flattest output, hardest gradients.",
        "ordered": (
            "An 8x8 Bayer matrix. Regular texture rather than noise, and cheap; it patterns "
            "large flat fills visibly."
        ),
        "floyd_steinberg": "Classic error diffusion over four neighbors. A good general default.",
        "atkinson": (
            "Diffuses only three quarters of the error, which keeps contrast high and light "
            "areas clean at the cost of some detail."
        ),
        "burkes": "Error diffusion over two rows; smoother than Floyd-Steinberg, slightly softer.",
        "sierra": "Error diffusion over three rows. Smooth gradients, the slowest of the family.",
        "sierra_lite": "A two-row, three-neighbor Sierra. Fast, with more visible structure.",
        "stucki": "Three-row diffusion with a wide kernel. Clean gradients, soft edges.",
        "jarvis": "Jarvis, Judice and Ninke: the widest kernel here. Smoothest, and the softest.",
    },
    "FitMode": {
        "contain": (
            "Scale to fit inside the panel, preserving aspect ratio, and center it on white. "
            "Nothing is lost and nothing is stretched."
        ),
        "cover": (
            "Scale to cover the panel, preserving aspect ratio, and crop the overflow. "
            "Anchored to the top, so headers survive."
        ),
        "stretch": "Scale to the panel exactly, distorting the aspect ratio if it differs.",
        "crop": (
            "No scaling: paste the image at the top left of a white canvas and crop whatever "
            "falls outside the panel."
        ),
    },
    "FrameFormat": {
        "packed": (
            "N bits per pixel, pixels left to right, rows top to bottom, each row padded to a "
            "byte boundary. Most grayscale controllers and index-addressed color panels."
        ),
        "planes": (
            "One 1-bit plane per ink, concatenated. The classic Waveshare black/white plus red "
            "layout, where two full-size buffers are clocked out in sequence."
        ),
        "indexed": (
            "One byte per pixel. Wasteful on the wire, and the simplest thing for a device or "
            "transport that does its own conversion."
        ),
        "png": (
            "A PNG image. What every transport that hands a picture to a library or a "
            "browser wants."
        ),
        "bmp": "A BMP image, for firmware with a BMP decoder and no PNG one.",
    },
    "ColorScheme": {
        "mono": "Black and white only.",
        "bwr": "Black, white and red: one spot ink.",
        "bwy": "Black, white and yellow: one spot ink.",
        "bwry": "Black, white, red and yellow: two spot inks.",
        "gray4": "Four levels of gray.",
        "gray8": "Eight levels of gray.",
        "gray16": "Sixteen levels of gray, as IT8951 controllers drive.",
        "spectra6": "E Ink Spectra 6: black, white, red, yellow, blue and green.",
        "acep7": "Advanced Color ePaper: the Spectra 6 inks plus orange.",
    },
}

#: The enumerations the configuration refers to, each with the heading it is
#: documented under. A description that names one of these headings is linked
#: to it automatically.
ENUM_SECTIONS: tuple[tuple[type[Enum], str], ...] = (
    (DitherMode, "Dither modes"),
    (FitMode, "Fit modes"),
    (FrameFormat, "Frame formats"),
    (ColorScheme, "Color schemes"),
)

ENUM_INTROS: dict[str, str] = {
    "FitMode": "How the screenshot is resized onto the panel, before rotation.",
    "FrameFormat": (
        "The byte layout of the delivered frame. Transports that hand a PIL image to a "
        "library never pack a frame at all, so they default to `png`."
    ),
}


# --------------------------------------------------------------------------- #
# Sections
# --------------------------------------------------------------------------- #

@dataclass
class Section:
    """One model rendered as one heading, a table and its validation rules."""

    heading: str
    model: type[BaseModel]
    #: Overrides the model's own docstring as the section's opening prose.
    intro: str = ""

    @property
    def anchor(self) -> str:
        return slugify(self.heading)

    def fields(self) -> list[tuple[str, FieldInfo]]:
        return list(self.model.model_fields.items())


def model_of(annotation: Any) -> type[BaseModel]:
    """The model behind a field annotation, unwrapping `list[...]` and `| None`."""
    for candidate in flatten(annotation):
        if isinstance(candidate, type) and issubclass(candidate, BaseModel):
            return candidate
    raise GenerationError(f"no model found in annotation {annotation!r}")


def flatten(annotation: Any) -> list[Any]:
    """Every leaf of a nested annotation, in order."""
    origin = typing.get_origin(annotation)
    if origin is None:
        return [annotation]
    out: list[Any] = []
    for arg in typing.get_args(annotation):
        out.extend(flatten(arg))
    return out


def build_sections() -> list[Section]:
    """The sections, in the order a user meets the keys."""
    top = Config.model_fields
    display = DisplayConfig.model_fields
    connections = ["home_assistant", "mqtt", "server"]
    nested = ["theme", "image", "lint", "render", "schedule", "transport", "pack", "esphome"]

    sections = [Section(name, model_of(top[name].annotation)) for name in connections]
    sections.append(
        Section(
            "Top-level keys",
            Config,
            intro=(
                "Every key at the root of the file. The three above have sections of "
                "their own, and each entry of `displays` is a [display](#displays)."
            ),
        )
    )
    sections.append(
        Section(
            "displays[]",
            DisplayConfig,
            intro=(
                "One entry per physical panel. `id` is the only required key: the keys "
                "beside it override something the panel catalog already knows, and the "
                "sections they point at are all optional too, so a display that names a "
                "catalog panel and a dashboard needs almost nothing else."
            ),
        )
    )
    sections.extend(
        Section(f"displays[].{name}", model_of(display[name].annotation))
        for name in nested
    )
    check_every_model_is_documented(sections)
    return sections


def check_every_model_is_documented(sections: list[Section]) -> None:
    """Fail if a model reachable from Config has no section of its own."""
    documented = {s.model for s in sections}
    missing = sorted(
        m.__name__ for m in reachable_models(Config) if m not in documented
    )
    if missing:
        raise GenerationError(
            "these models are reachable from Config but have no section in "
            f"scripts/gen_docs.py: {', '.join(missing)}"
        )


def reachable_models(model: type[BaseModel]) -> set[type[BaseModel]]:
    found: set[type[BaseModel]] = {model}
    for info in model.model_fields.values():
        for leaf in flatten(info.annotation):
            if isinstance(leaf, type) and issubclass(leaf, BaseModel) and leaf not in found:
                found |= reachable_models(leaf)
    return found


# --------------------------------------------------------------------------- #
# Rendering types, defaults and descriptions
# --------------------------------------------------------------------------- #

def anchors_by_model(sections: list[Section]) -> dict[type[BaseModel], str]:
    return {s.model: s.anchor for s in sections}


def render_type(annotation: Any, anchors: dict[type[BaseModel], str]) -> str:
    """A readable rendering of a field's type, for the table."""
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    if origin in (types.UnionType, typing.Union):
        parts = [render_type(a, anchors) for a in args]
        # A field that takes either a duration string or a number of seconds is
        # far clearer shown by example than as `str | float`.
        if str in args and (float in args or int in args):
            parts[args.index(str)] = '`"5m"`'
        return " | ".join(parts)
    if origin is typing.Literal:
        return " | ".join(f"`{a}`" for a in args)
    if origin in (list, set, frozenset):
        return f"`{origin.__name__}` of {render_type(args[0], anchors)}"
    if origin is dict:
        key, value = (render_type(a, anchors) for a in args)
        return f"`dict` of {key} to {value}"
    if origin is tuple:
        return "`[" + ", ".join(render_type(a, anchors).strip("`") for a in args) + "]`"
    if annotation is type(None):
        return "`None`"
    if isinstance(annotation, type) and issubclass(annotation, Enum):
        return " | ".join(f"`{member.value}`" for member in annotation)
    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        anchor = anchors.get(annotation)
        name = annotation.__name__
        return f"[section](#{anchor})" if anchor else f"`{name}`"
    if isinstance(annotation, type):
        return f"`{annotation.__name__}`"
    return f"`{annotation}`"


def render_constraints(info: FieldInfo) -> str:
    """The numeric bounds pydantic will enforce, as a suffix for the type cell."""
    bounds: dict[str, Any] = {}
    for item in info.metadata:
        for kind in ("ge", "gt", "le", "lt"):
            value = getattr(item, kind, None)
            if value is not None:
                bounds[kind] = value
    low = bounds.get("ge", bounds.get("gt"))
    high = bounds.get("le", bounds.get("lt"))
    if low is not None and high is not None:
        return f", {low} to {high}"
    if low is not None:
        return f", at least {low}"
    if high is not None:
        return f", at most {high}"
    return ""


def render_default(info: FieldInfo) -> str:
    if info.is_required():
        return "**required**"
    try:
        value = info.get_default(call_default_factory=True)
    except TypeError:  # a factory that wants validated data; none here today
        return "*(computed)*"
    return render_value(value)


def render_value(value: Any) -> str:
    if isinstance(value, BaseModel):
        return "*section defaults*"
    if value is None:
        return "*unset*"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, Enum):
        return f"`{value.value}`"
    if isinstance(value, str):
        return f"`\"{value}\"`" if value else "`\"\"`"
    if isinstance(value, (list, tuple)) and not value:
        return "`[]`"
    if isinstance(value, dict) and not value:
        return "`{}`"
    return f"`{value}`"


def cell(text: str) -> str:
    """Text safe to drop into a Markdown table cell."""
    return " ".join(text.split()).replace("|", "\\|")


def link_sections(text: str) -> str:
    """Turn a mention of one of this page's headings into a link to it."""
    for heading in [h for _, h in ENUM_SECTIONS] + ["Transport options"]:
        text = text.replace(heading, f"[{heading}](#{slugify(heading)})")
    return text


def slugify(heading: str) -> str:
    """A GitHub-style anchor for a heading."""
    slug = heading.strip().lower()
    slug = re.sub(r"[^\w\s-]", "", slug)
    return re.sub(r"\s+", "-", slug)


def docstring(obj: Any) -> str:
    """An object's own docstring, never one inherited from a base class."""
    doc = obj.__dict__.get("__doc__") if isinstance(obj, type) else obj.__doc__
    return inspect.cleandoc(doc).strip() if doc else ""


# --------------------------------------------------------------------------- #
# Validators
# --------------------------------------------------------------------------- #

def validator_rules(model: type[BaseModel]) -> list[str]:
    """One line per validator on this model, taken from its docstring."""
    decorators = model.__pydantic_decorators__
    rules: list[str] = []
    for name, decorator in list(decorators.field_validators.items()) + list(
        decorators.model_validators.items()
    ):
        func = getattr(decorator.func, "__func__", decorator.func)
        doc = docstring(func)
        if not doc:
            raise GenerationError(
                f"{model.__name__}.{name} is a validator with no docstring, so the "
                "reference cannot describe what it enforces. Give it one."
            )
        rules.append(" ".join(doc.split()))
    return rules


# --------------------------------------------------------------------------- #
# Transports
# --------------------------------------------------------------------------- #

def options_used(cls: type[Transport]) -> dict[str, bool]:
    """Every `self.option("x")` the class reads, mapped to whether it is required."""
    tree = ast.parse(textwrap.dedent(inspect.getsource(cls)))
    used: dict[str, bool] = {}
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (
            isinstance(func, ast.Attribute)
            and func.attr == "option"
            and isinstance(func.value, ast.Name)
            and func.value.id == "self"
        ):
            continue
        if not (node.args and isinstance(node.args[0], ast.Constant)):
            continue
        key = node.args[0].value
        required = any(
            kw.arg == "required" and getattr(kw.value, "value", False) is True
            for kw in node.keywords
        )
        used[key] = used.get(key, False) or required
    return used


def check_transport_options() -> dict[str, dict[str, bool]]:
    """Fail if a transport reads an option it does not document."""
    required_by: dict[str, dict[str, bool]] = {}
    problems: list[str] = []
    for name, cls in sorted(available_transports().items()):
        used = options_used(cls)
        required_by[name] = used
        undocumented = sorted(set(used) - set(cls.options_doc))
        if undocumented:
            problems.append(
                f"{cls.__name__} reads {', '.join(repr(o) for o in undocumented)} "
                "but does not describe it in options_doc"
            )
    if problems:
        raise GenerationError("; ".join(problems))
    return required_by


# --------------------------------------------------------------------------- #
# The configuration page
# --------------------------------------------------------------------------- #

def render_configuration() -> str:
    sections = build_sections()
    anchors = anchors_by_model(sections)
    required_by = check_transport_options()

    out: list[str] = [
        f"<!-- {BANNER} -->",
        "",
        "# Configuration reference",
        "",
        f"> {BANNER}",
        "> Edit the `Field(description=...)` text in `src/maverick/config.py`, or the prose",
        "> in `docs/reference/_configuration.intro.md`, then run `python scripts/gen_docs.py`.",
        "",
        read_include("_configuration.intro.md"),
        "",
    ]

    for section in sections:
        out.append(f"## {section.heading}")
        out.append("")
        intro = section.intro or docstring(section.model)
        if intro:
            out.append(intro)
            out.append("")
        out.append("| Key | Type | Default | Description |")
        out.append("| --- | --- | --- | --- |")
        for name, info in section.fields():
            if not info.description:
                raise GenerationError(
                    f"{section.model.__name__}.{name} has no description, so the "
                    "reference would document it as a blank. Add one in config.py."
                )
            rendered_type = render_type(info.annotation, anchors) + render_constraints(info)
            out.append(
                f"| `{name}` | {cell(rendered_type)} "
                f"| {cell(render_default(info))} "
                f"| {link_sections(cell(info.description))} |"
            )
        out.append("")
        rules = validator_rules(section.model)
        if rules:
            out.append("**Validation.** " + " ".join(rules))
            out.append("")

    out.append(render_enums())
    out.append(render_transports(required_by))
    return "\n".join(out).rstrip() + "\n"


def render_enums() -> str:
    out = ["## Enumerations", ""]
    for enum_cls, heading in ENUM_SECTIONS:
        values = ENUM_VALUE_DOCS[enum_cls.__name__]
        undocumented = [m.value for m in enum_cls if m.value not in values]
        if undocumented:
            raise GenerationError(
                f"{enum_cls.__name__} has values with no description in "
                f"scripts/gen_docs.py: {', '.join(undocumented)}"
            )
        out.append(f"### {heading}")
        out.append("")
        intro = enum_cls.__doc__ or ENUM_INTROS.get(enum_cls.__name__, "")
        if intro:
            out.append(" ".join(intro.split()))
            out.append("")
        out.append("| Value | Meaning |")
        out.append("| --- | --- |")
        for member in enum_cls:
            out.append(f"| `{member.value}` | {cell(values[member.value])} |")
        out.append("")
    return "\n".join(out)


def render_transports(required_by: dict[str, dict[str, bool]]) -> str:
    out = [
        "## Transport options",
        "",
        "`displays[].transport.type` picks a transport; every other key in that section is "
        "the transport's own. They are listed here rather than in the table above because "
        "`TransportConfig` allows extra keys, so the transport, not the model, owns them. "
        "An option a transport does not recognize is ignored rather than rejected.",
        "",
    ]
    for name, cls in sorted(available_transports().items()):
        used = required_by[name]
        out.append(f"### `{name}`")
        out.append("")
        delivery = (
            "Pushes to the device: delivery succeeds or fails now."
            if cls.pushes
            else "Publishes the frame for the device to collect, so a delivery is *pending* "
            "until the device fetches it."
        )
        out.append(f"{cls.description}. {delivery}")
        out.append("")
        if not cls.options_doc:
            out.append("Takes no options of its own.")
            out.append("")
            continue
        out.append("| Option | Required | Description |")
        out.append("| --- | --- | --- |")
        for option, description in cls.options_doc.items():
            required = "yes" if used.get(option) else "no"
            out.append(f"| `{option}` | {required} | {cell(description)} |")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------- #
# The panel catalog page
# --------------------------------------------------------------------------- #

def render_panels() -> str:
    out: list[str] = [
        f"<!-- {BANNER} -->",
        "",
        "# Panel catalog",
        "",
        f"> {BANNER}",
        "> Edit `src/maverick/devices/panels.yaml`, or the prose in",
        "> `docs/reference/_panels.intro.md`, then run `python scripts/gen_docs.py`.",
        "",
        read_include("_panels.intro.md"),
        "",
    ]
    for vendor, panels in panels_by_vendor().items():
        out.append(f"## {vendor}")
        out.append("")
        out.append(
            "| id | Name | Resolution | Color scheme | dpi | Partial refresh "
            "| Full-refresh cadence | Default transport | ESPHome model | Notes |"
        )
        out.append("| --- | --- | --- | --- | --- | --- | --- | --- | --- | --- |")
        for panel in panels:
            esphome = f"`{panel.esphome_model}`" if panel.esphome_model else "—"
            out.append(
                f"| `{panel.id}` | {cell(panel.name)} | {panel.width}×{panel.height} "
                f"| `{panel.color_scheme.value}` | {panel.dpi} "
                f"| {'yes' if panel.supports_partial else 'no'} "
                f"| {cell(_full_refresh_cadence(panel))} "
                f"| `{panel.default_transport}` | {esphome} | {cell(panel.notes)} |"
            )
        out.append("")
    return "\n".join(out).rstrip() + "\n"


def _full_refresh_cadence(panel: PanelProfile) -> str:
    if not panel.supports_partial:
        return "every render — the panel has no partial-refresh mode"
    if panel.full_refresh_every:
        return f"every {panel.full_refresh_every} frames"
    return "never forced — partial refresh only, unless a display overrides it"


# --------------------------------------------------------------------------- #
# The transports page
# --------------------------------------------------------------------------- #

def render_transports_page() -> str:
    required_by = check_transport_options()
    out: list[str] = [
        f"<!-- {BANNER} -->",
        "",
        "# Transport reference",
        "",
        f"> {BANNER}",
        "> Edit `options_doc` and the class docstring in `src/maverick/transports/*.py`, "
        "or the prose in `docs/reference/_transports/<name>.md`, then run",
        "> `python scripts/gen_docs.py`.",
        "",
        "`displays[].transport.type` picks one of these. See "
        "[Transport options](configuration.md#transport-options) for how the options "
        "below relate to `TransportConfig`.",
        "",
    ]
    for name, cls in sorted(available_transports().items()):
        used = required_by[name]
        mode = "push" if cls.pushes else "pull"
        out.append(f"## `{name}`")
        out.append("")
        out.append(f"**{mode}** — {cls.description}.")
        out.append("")
        out.append(read_include(f"_transports/{name}.md"))
        out.append("")
        if not cls.options_doc:
            out.append("Takes no options of its own.")
            out.append("")
            continue
        out.append("| Option | Required | Description |")
        out.append("| --- | --- | --- |")
        for option, description in cls.options_doc.items():
            required = "yes" if used.get(option) else "no"
            out.append(f"| `{option}` | {required} | {cell(description)} |")
        out.append("")
    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# The CLI page
# --------------------------------------------------------------------------- #

def _subparsers_action(parser: argparse.ArgumentParser) -> argparse._SubParsersAction:
    for action in parser._actions:  # noqa: SLF001
        if isinstance(action, argparse._SubParsersAction):  # noqa: SLF001
            return action
    raise GenerationError("build_parser() has no subcommands")


def _find_option(parser: argparse.ArgumentParser, flag: str) -> argparse.Action:
    for action in parser._actions:  # noqa: SLF001
        if flag in action.option_strings:
            return action
    raise GenerationError(f"build_parser() has no {flag!r} option")


def _subcommand_help(sub_action: Any, name: str) -> str:
    for choice_action in sub_action._choices_actions:  # noqa: SLF001
        if choice_action.dest == name:
            return choice_action.help or ""
    return ""


def _render_flag_default(action: argparse.Action) -> str:
    if action.nargs == 0:  # store_true / store_false
        return f"`{str(bool(action.default)).lower()}`"
    if action.default is None:
        return "*unset*"
    return f"`{action.default}`"


def _render_flag_help(action: argparse.Action) -> str:
    help_text = action.help or ""
    if action.choices:
        help_text = f"{help_text} One of: {', '.join(str(c) for c in action.choices)}.".strip()
    return help_text


def _render_flags_table(actions: list[argparse.Action]) -> list[str]:
    out = ["| Flag | Default | Description |", "| --- | --- | --- |"]
    for action in actions:
        flags = ", ".join(f"`{f}`" for f in action.option_strings)
        default = cell(_render_flag_default(action))
        help_text = cell(_render_flag_help(action))
        out.append(f"| {flags} | {default} | {help_text} |")
    return out


def render_cli() -> str:
    parser = build_parser()
    out: list[str] = [
        f"<!-- {BANNER} -->",
        "",
        "# CLI reference",
        "",
        f"> {BANNER}",
        "> Edit the `help=` text and arguments in `src/maverick/cli.py`, or the prose in",
        "> `docs/reference/_cli.intro.md`, then run `python scripts/gen_docs.py`.",
        "",
        read_include("_cli.intro.md"),
        "",
        "## Global options",
        "",
        "Given before the subcommand: `maverick -c config.yaml render kitchen`.",
        "",
    ]
    global_actions = [
        _find_option(parser, "--config"),
        _find_option(parser, "--log-level"),
        _find_option(parser, "--verbose"),
    ]
    out.extend(_render_flags_table(global_actions))
    out.append("")

    out.append("## Subcommands")
    out.append("")
    sub_action = _subparsers_action(parser)
    for name, subparser in sub_action.choices.items():
        out.append(f"### `maverick {name}`")
        out.append("")
        help_text = _subcommand_help(sub_action, name)
        if help_text:
            out.append(help_text)
            out.append("")
        positionals = [
            a for a in subparser._actions if not a.option_strings  # noqa: SLF001
        ]
        optionals = [
            a
            for a in subparser._actions  # noqa: SLF001
            if a.option_strings and "-h" not in a.option_strings
        ]
        if positionals:
            out.append("| Argument | Description |")
            out.append("| --- | --- |")
            for action in positionals:
                suffix = " (optional)" if action.nargs == "?" else ""
                out.append(f"| `{action.dest}`{suffix} | {cell(action.help or '')} |")
            out.append("")
        if optionals:
            out.extend(_render_flags_table(optionals))
            out.append("")

    out.append("## Environment variables")
    out.append("")
    out.append("| Variable | Description |")
    out.append("| --- | --- |")
    for name, description in ENVIRONMENT_VARIABLES:
        out.append(f"| `{name}` | {cell(description)} |")
    out.append("")

    out.append("## Exit codes")
    out.append("")
    out.append("| Code | Meaning |")
    out.append("| --- | --- |")
    for code, meaning in EXIT_CODES:
        out.append(f"| `{code}` | {cell(meaning)} |")
    out.append("")

    return "\n".join(out).rstrip() + "\n"


# --------------------------------------------------------------------------- #
# The OpenAPI document
# --------------------------------------------------------------------------- #

def render_openapi() -> str:
    """FastAPI's own description of every route, as JSON.

    Built around a default ``Config`` rather than anyone's config file, so the
    document describes the routes themselves and not one deployment: with no
    displays configured the path parameters stay generic and no base URL or
    token leaks into the output.

    The content is FastAPI's, so a FastAPI upgrade can legitimately change it
    (the schema dialect, say). ``--check`` will fail; regenerating is the fix.
    """
    application = Application(Config())
    document = create_app(application).openapi()
    if not document.get("paths"):
        raise GenerationError("create_app() produced an OpenAPI document with no paths")
    return json.dumps(document, indent=2) + "\n"


def read_include(name: str) -> str:
    path = DOCS / name
    if not path.exists():
        raise GenerationError(f"missing hand-written include: {path.relative_to(ROOT)}")
    return path.read_text(encoding="utf-8").strip()


# --------------------------------------------------------------------------- #
# Entry point
# --------------------------------------------------------------------------- #

PAGES: dict[str, Any] = {
    "configuration.md": render_configuration,
    "panels.md": render_panels,
    "transports.md": render_transports_page,
    "cli.md": render_cli,
    "openapi.json": render_openapi,
}


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--check",
        action="store_true",
        help="do not write anything; exit 1 if a page is out of date",
    )
    args = parser.parse_args(argv)

    try:
        rendered = {name: render() for name, render in PAGES.items()}
    except GenerationError as exc:
        print(f"gen_docs: {exc}", file=sys.stderr)
        return 1

    stale: list[str] = []
    for name, content in rendered.items():
        path = DOCS / name
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if args.check:
            if current != content:
                stale.append(str(path.relative_to(ROOT)))
            continue
        if current == content:
            print(f"unchanged {path.relative_to(ROOT)}")
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(f"wrote     {path.relative_to(ROOT)}")

    if stale:
        print(
            "gen_docs: out of date: "
            + ", ".join(stale)
            + "\nRun `python scripts/gen_docs.py` and commit the result.",
            file=sys.stderr,
        )
        return 1
    if args.check:
        print("gen_docs: reference pages are up to date")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
